M48
; DRILL file {KiCad 8.0.0} date 2024-04-03T18:38:56+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-03T18:38:56+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X80.0Y-85.0
X80.0Y-130.0
X150.0Y-85.0
X150.0Y-130.0
X220.0Y-85.0
X220.0Y-130.0
M30
